### ISSUE TITLE
Corp/Alliance Roles Randomly removed

### ISSUE THREAD

**Issue by tim7433** [Jimmy062006/Opux#18]
I am having an issue where the roles are being removed for corp and alliance at different times usually just once a week. 

I checked my server metrics and it was not an issue there.

The logs just show that it removed roles and users reauthed or the !reauth was used to restore user roles.

**Comment by joshbrown50** [comment]
This happens to me as well. I think it's ESI failing to respond

**Comment by j-novak** [comment]
Same here. Wouldn't it be better to not adjust roles/anything if the ESI call fails?

**Comment by Jimmy062006** [comment]
The issue is that the return is null for both an error and the fact they have no alliance.

**Comment by j-novak** [comment]
wow what a piece of crap their API is if it's like that :-/

**Comment by Jimmy062006** [comment]
Please try 6d8f6e5

**Comment by Jimmy062006** [comment]
Any update to this issue ? I will close it in a few days if not.

**Comment by tim7433** [comment]
has not resurfaced since patch. consider closed
