### ISSUE TITLE
More customization for killbot

### ISSUE THREAD

**Issue by midnightsteel** [Jimmy062006/Opux#21]
It would be nice to be able to specify certain types of killbot filtering. Like shiptype and locations

**Comment by BroodLK** [comment]
The bot is not a substitute for Zkill...

**Comment by tim7433** [comment]
You can use the radius for location and value of kill as a filter but anything else just go look at zkill IMO.

**Comment by Jimmy062006** [comment]
The idea of the kill feed is exactly that its a feed of your corps/alliances kills and losses or all kills for a radius around a system. It is not to replace zKill.
