### ISSUE TITLE
Auth not possible using e.g. Opera or Chrome

### ISSUE THREAD

**Issue by MyUncleSam** [Jimmy062006/Opux#26]
Hi there,

some users reported, that they are not able to authenticate using chrome. I checked that and all I got was the source code of the page instead of the page itselfe. Can you please check that?

Screenshot:
![grafik](https://user-images.githubusercontent.com/12820919/32832548-26aac4f6-c9fc-11e7-9926-6b43818bf97d.png)

**Comment by BroodLK** [comment]
I exclusively used chrome, never had this issue, nor have I heard it reported on Chrome from anyone. I have heard of a report of this on Opera though.

**Comment by MyUncleSam** [comment]
I also tried the private mode from chrome which is using no extension and this is also not working. So for me it looks like a webserver problem.

(Maybe using a simple php script would be better?!?)

**Comment by Jimmy062006** [comment]
This is not an issue with the webserver as it doesn't run one per say. It's serving static html content that any browser can handle a d display. Please check any antivirus or anti-spyware software you are running as this can interfere with things in some browsers

**Comment by tim7433** [comment]
I can confirm that this is not an issue for any of my users that have authed. perhaps this is a failure on the installers setup of the bot? Try accessing it from your cell phone using cellular connection.

**Comment by MyUncleSam** [comment]
I found the problem. For security reasons I proxy pass the bot port using apache2. This seems to pass the wrong mime type in some cases.
If anyone has a solution how to tell apache to redirect the correct mime type - please tell me :-)

**Comment by Jimmy062006** [comment]
I proxy pass using apache just fine. When I have my pc running I will find the settings I use.

**Comment by Jimmy062006** [comment]
I'm also not sure what security benefits it would add though

**Comment by MyUncleSam** [comment]
At the moment a sll certificate.

**Comment by Jimmy062006** [comment]
An SSL cert will not make anything more secure you don't put any information in to it.

**Comment by MyUncleSam** [comment]
You said you have a working apache2 proxy config which is working for you. Can you send it?

**Comment by MyUncleSam** [comment]
Ok @Jimmy062006 I found a solution and it would be great if you could add it to your solution:
Inside your "Functions.cs" you user "... await response.WriteContentAsync(..." to send the webpage. If you insert this line before all of them the content type is set to html and all my browsers displays it correctly:

response.Headers.Add("Content-Type", "text/html");

**Comment by Jimmy062006** [comment]
Whilst I understand adding that is needed and will be done I don't understand what protection adding ssl adds. Could you explain what you think that is adding ?

**Comment by MyUncleSam** [comment]
I have no idea if ssl is protecting the token transfer or not. But all in all if someone tells you to authenticate it would be better to do it on secured ways. Maybe it is only optical but I want to do it this way (because my paranoid members would never even think about logging in if it is not a secured page - like they want to login to their banking account).

**Comment by Jimmy062006** [comment]
Auth is done on ccps SSL site. All opux non ask site does is give you a link to that site. The return data is also provided in the url visited by CCP so adding SSL does nothing.

**Comment by MyUncleSam** [comment]
Ok but I hope you understand my reasons, I understand yours too to not need it. But I am happy that I found a solution which is applied by you into the bot.

**Comment by MyUncleSam** [comment]
sorry to ask again @Jimmy062006 but I wanted to update my bot and saw that the header is still missing in your function file. Is there any possibility that you add it soon?

`response.Headers.Add("Content-Type", "text/html");`
