### ISSUE TITLE
Enhancement Request - Limit Fleetup notifications and/or reverse sort order

### ISSUE THREAD

**Issue by k9by** [Jimmy062006/Opux#37]
With the new format of the fleetup notifications, there are about 3 notifications on the screen. Currently we have over 12 ops in fleetup, so we have to scroll back about 4 screens to get to the "next" op, as the next op is the first one in the list. Would it be possible to limit the number of fleetup notifications when using !ops, either by count (ie: 3) or by time (only next 24 hours). Another idea would be to reverse the order so the furthest fleet is listed first, and the nearest fleet is last. That way the users don't need to scroll to find the next fleet. Another variant would be !op which only displays the next op, not all of them, but I still think limiting and/or reordering would be a good idea.

If you accept patches, I could work on some and submit for approval.

**Comment by Jimmy062006** [comment]
What about adding an !op command that returns the next singular op

**Comment by k9by** [comment]
Still checking with the alliance but it sounds like !op or !opnext would be a reasonable solution.
