### ISSUE TITLE
Possible defect - Discord Link Preview turned off, no fleetup info displayed

### ISSUE THREAD

**Issue by k9by** [Jimmy062006/Opux#38]
If you go in to Discord Settings -> App Settings -> Text & Images -> Link Preview and turn this option off, all the Fleetup notifications are reduced to a single line each (the html preview is hidden), but there is nothing displayed besides the bot name. I believe there should be a hyperlink that users can click on to launch the html view in to external browser.

**Comment by Jimmy062006** [comment]
Unfortunately Discord does not allow me to send a message for people with previews disabled. It will then look a mess for people with it enabled. Just setup the roles correctly so that only the bot can embed/load previews.

**Comment by Jimmy062006** [comment]
This should be it.

![image](https://user-images.githubusercontent.com/4639349/34968065-d73b9cc2-fa5e-11e7-8ffc-b421a6998d22.png)

**Comment by k9by** [comment]
We have that on. If the user chooses not to show link preview, it's on them.
