### ISSUE TITLE
TeamSpeak 3 Support

### ISSUE THREAD

**Issue by Jimmy062006** [Jimmy062006/Opux#41]
I'd like a show of hands for support of Teamspeak auth module.

The way this would work is the user would be asked to set there nickname to there in game name and then type `!ts3` in discord. This would then check they are authed on discord and then assign there TS3 user permissions and store any relevant teamspeak details for role removal at a later date.

**Comment by tim7433** [comment]
+10000000

**Comment by joshbrown50** [comment]
I would love this
